export default {
  content: [
    './**/*.php',
    './assets/**/*.js',
  ],
  safelist: [
    'border-theme-1',
    'border-theme-2',
    'border-theme-3',
    'border-theme-4',
    'border-theme-5',

    'text-black',
    'text-theme-1',
    'text-theme-1!',
    'text-theme-2',
    'text-theme-2!',
    'text-theme-3',
    'text-theme-3!',
    'text-theme-4',
    'text-theme-4!',
    'text-theme-5',
    'text-theme-5!',

    'bg-theme-1',
    'bg-theme-1/50',
    'bg-theme-2',
    'bg-theme-2/50',
    'bg-theme-3',
    'bg-theme-3/50',
    'bg-theme-4',
    'bg-theme-4/50',
    'bg-theme-5',
    'bg-theme-5/50',

    'from-theme-1',
    'from-theme-1/50',
    'from-theme-2',
    'from-theme-2/50',
    'from-theme-3',
    'from-theme-3/50',
    'from-theme-4',
    'from-theme-4/50',
    'from-theme-5',
    'from-theme-5/50',

    'to-theme-1/50',
    'to-theme-2/50',
    'to-theme-3/50',
    'to-theme-4/50',
    'to-theme-5/50',

    'bg-linear-to-t',
    'bg-linear-to-tr',
    'bg-linear-to-r',
    'bg-linear-to-br',
    'bg-linear-to-b',
    'bg-linear-to-bl',
    'bg-linear-to-l',
    'bg-linear-to-tl',
  ],
  theme: {
    extend: {
      colors: {
        'theme-1': 'var(--theme-1)',
        'theme-2': 'var(--theme-2)',
        'theme-3': 'var(--theme-3)',
        'theme-4': 'var(--theme-4)',
        'theme-5': 'var(--theme-5)',
      },
    },
  },
}
